package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmInventories extends javax.swing.JFrame {

    private FinvoryController controller;
    private Inventory currentInventory = null;

    /**
     * Creates new form FrmInventories
     */
    public FrmInventories(FinvoryController controller) {
        initComponents();
        this.controller = controller;
        this.setLocationRelativeTo(null);
        setupTableNonEditable();
    }

    public FrmInventories() {
        initComponents();
    }

    private void setupTableNonEditable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabProducts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFindInventory = new javax.swing.JButton();
        txtCountryInventory = new javax.swing.JLabel();
        txtCityInventory = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProducts = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuHandle = new javax.swing.JMenu();
        itemProducts = new javax.swing.JMenuItem();
        itemObsoleteProducts = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAddNewInventory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Inventario:");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel2.setText("País:");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("Ciudad:");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel4.setText("Productos:");

        btnFindInventory.setBackground(new java.awt.Color(0, 123, 0));
        btnFindInventory.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnFindInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnFindInventory.setText("BUSCAR");
        btnFindInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFindInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCountryInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCityInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(btnFindInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtCountryInventory)
                            .addComponent(txtCityInventory)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnFindInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 224, 224));

        tabProducts.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        tabProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProducts);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Finvory");

        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        mnuHandle.setText("Gestión");

        itemProducts.setText("Productos");
        itemProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductsActionPerformed(evt);
            }
        });
        mnuHandle.add(itemProducts);

        itemObsoleteProducts.setText("Productos Obsoletos");
        itemObsoleteProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemObsoleteProductsActionPerformed(evt);
            }
        });
        mnuHandle.add(itemObsoleteProducts);

        jMenuBar1.add(mnuHandle);

        jMenu2.setText("Inventarios");

        itemAddNewInventory.setText("Añadir Nuevo Inventario");
        itemAddNewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddNewInventoryActionPerformed(evt);
            }
        });
        jMenu2.add(itemAddNewInventory);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInventoryActionPerformed
        String query = txtName.getText().trim();

        if (query.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba un nombre.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            ArrayList<Inventory> matches = controller.findInventoriesByPartialName(query);

            if (matches.isEmpty()) {
                handleNoMatches();
            } else if (matches.size() == 1) {
                handleSingleMatch(matches.get(0));
            } else {
                handleMultipleMatches(matches);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFindInventoryActionPerformed

    private void itemProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductsActionPerformed
        if (this.currentInventory != null) {
            FrmProducts win = new FrmProducts(controller, this.currentInventory);
            win.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    FrmInventories.this.setVisible(true);
                }
            });
            win.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y seleccionar un inventario.");
        }
    }//GEN-LAST:event_itemProductsActionPerformed

    private void itemObsoleteProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemObsoleteProductsActionPerformed
        FrmObsoleteInventories win = new FrmObsoleteInventories(this, true, controller);
        this.setVisible(false);
        win.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmInventories.this.setVisible(true);
                if (currentInventory != null) {
                    populateTable();
                }
            }
        });
        win.setVisible(true);
    }//GEN-LAST:event_itemObsoleteProductsActionPerformed

    private void itemAddNewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddNewInventoryActionPerformed
        FrmAddNewInventory win = new FrmAddNewInventory(this, true, controller);
        this.setVisible(false);
        win.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmInventories.this.setVisible(true);
            }
        });
        win.setVisible(true);
    }//GEN-LAST:event_itemAddNewInventoryActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void handleNoMatches() {
        JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        clearFields();
    }

    private void handleSingleMatch(Inventory inventory) {
        this.currentInventory = inventory;
        updateInterface();
    }

    private void handleMultipleMatches(ArrayList<Inventory> matches) {
        FrmInventorySelector selector = new FrmInventorySelector(this, true, matches);
        selector.setVisible(true);
        this.currentInventory = selector.getSelectedInventory();
        if (this.currentInventory != null) {
            updateInterface();
        } else {
            clearFields();
        }
    }

    private void updateInterface() {
        if (currentInventory.getAddress() != null) {
            txtCountryInventory.setText(currentInventory.getAddress().getCountry());
            txtCityInventory.setText(currentInventory.getAddress().getCity());
        } else {
            txtCountryInventory.setText("-");
            txtCityInventory.setText("-");
        }
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);
        List<Object[]> rows = controller.getInventoryTableData(currentInventory);
        for (Object[] row : rows) {
            model.addRow(row);
        }
    }

    private void clearFields() {
        txtCountryInventory.setText("");
        txtCityInventory.setText("");
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);
        this.currentInventory = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindInventory;
    private javax.swing.JMenuItem itemAddNewInventory;
    private javax.swing.JMenuItem itemObsoleteProducts;
    private javax.swing.JMenuItem itemProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuHandle;
    private javax.swing.JTable tabProducts;
    private javax.swing.JLabel txtCityInventory;
    private javax.swing.JLabel txtCountryInventory;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
