package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.FinvoryApp;
import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.controller.*;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmInventories extends javax.swing.JFrame {

    private FinvoryController controller;
    private Inventory currentInventory = null;

    /**
     * Creates new form FrmInventories
     */
    public FrmInventories(FinvoryController controller) {
        initComponents();
        this.controller = controller;
        this.setLocationRelativeTo(null);
        setupTableNonEditable();
        fillInventoryCombo();
        FinvoryApp.setIcon(this);
    }

    public FrmInventories() {
        initComponents();
        FinvoryApp.setIcon(this);
    }

    private void setupTableNonEditable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabProducts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInventoryName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        txtCountryInventory = new javax.swing.JLabel();
        txtCityInventory = new javax.swing.JLabel();
        cmbInventories = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProducts = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemPrincipalMenu = new javax.swing.JMenuItem();
        mnuHandle = new javax.swing.JMenu();
        itemProducts = new javax.swing.JMenuItem();
        itemObsoleteProducts = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAddNewInventory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        lblInventoryName.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblInventoryName.setText("Nombre del Inventario:");

        lblCountry.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblCountry.setText("País:");

        lblCity.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblCity.setText("Ciudad:");

        lblProduct.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblProduct.setText("Productos:");

        cmbInventories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInventories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInventoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProduct)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCountryInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lblCity)
                        .addGap(18, 18, 18)
                        .addComponent(txtCityInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(474, 474, 474))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbInventories, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventoryName)
                    .addComponent(cmbInventories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(lblCity)
                    .addComponent(txtCountryInventory)
                    .addComponent(txtCityInventory))
                .addGap(8, 8, 8)
                .addComponent(lblProduct)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 224, 224));

        tabProducts.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        tabProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProducts);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Finvory");

        itemPrincipalMenu.setText("Menu Principal");
        itemPrincipalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrincipalMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemPrincipalMenu);

        jMenuBar1.add(jMenu1);

        mnuHandle.setText("Productos");

        itemProducts.setText("Productos");
        itemProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductsActionPerformed(evt);
            }
        });
        mnuHandle.add(itemProducts);

        itemObsoleteProducts.setText("Productos Obsoletos");
        itemObsoleteProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemObsoleteProductsActionPerformed(evt);
            }
        });
        mnuHandle.add(itemObsoleteProducts);

        jMenuBar1.add(mnuHandle);

        jMenu2.setText("Inventarios");

        itemAddNewInventory.setText("Añadir Nuevo Inventario");
        itemAddNewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddNewInventoryActionPerformed(evt);
            }
        });
        jMenu2.add(itemAddNewInventory);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductsActionPerformed
        onOpenProducts();
    }//GEN-LAST:event_itemProductsActionPerformed

    private void itemObsoleteProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemObsoleteProductsActionPerformed
        onOpenObsoleteProducts();
    }//GEN-LAST:event_itemObsoleteProductsActionPerformed

    private void itemAddNewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddNewInventoryActionPerformed
        onAddNewInventory();
    }//GEN-LAST:event_itemAddNewInventoryActionPerformed

    private void itemPrincipalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrincipalMenuActionPerformed
        onClose();
    }//GEN-LAST:event_itemPrincipalMenuActionPerformed

    private void cmbInventoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInventoriesActionPerformed
        onInventoryComboSelection();
    }//GEN-LAST:event_cmbInventoriesActionPerformed
    private void handleNoMatches() {
        JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        clearFields();
    }

    private void handleSingleMatch(Inventory inventory) {
        this.currentInventory = inventory;
        updateInterface();
    }

    private void handleMultipleMatches(ArrayList<Inventory> matches) {
        FrmInventorySelector selector = new FrmInventorySelector(this, true, matches);
        selector.setVisible(true);
        this.currentInventory = selector.getSelectedInventory();
        if (this.currentInventory != null) {
            updateInterface();
        } else {
            clearFields();
        }
    }

    private void updateInterface() {
        if (currentInventory.getAddress() != null) {
            txtCountryInventory.setText(currentInventory.getAddress().getCountry());
            txtCityInventory.setText(currentInventory.getAddress().getCity());
        } else {
            txtCountryInventory.setText("-");
            txtCityInventory.setText("-");
        }
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);

        if (currentInventory == null) {
            return; 
        }
        
        List<Object[]> rows = controller.inventoryController.getInventoryTableData(currentInventory);
        for (Object[] row : rows) {
            model.addRow(row);

        }
    }

    private void clearFields() {
        txtCountryInventory.setText("");
        txtCityInventory.setText("");
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);
        this.currentInventory = null;

    }

    private void handleSearchResult(ArrayList<Inventory> matches) {
        if (matches == null || matches.isEmpty()) {
            handleNoMatches();
            return;
        }
        if (matches.size() == 1) {
            handleSingleMatch(matches.get(0));
            return;
        }
        handleMultipleMatches(matches);
    }

    private void onOpenProducts() {
        if (currentInventory == null) {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y seleccionar un inventario.");
            return;
        }

        FrmProducts products = new FrmProducts(controller.productController, controller, currentInventory);
        products.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmInventories.this.setVisible(true);
            }
        });

        products.setVisible(true);
        this.setVisible(false);
    }

    private void onOpenObsoleteProducts() {
        FrmObsoleteInventories obsoleteInventorie = new FrmObsoleteInventories(this, true, controller);
        this.setVisible(false);

        obsoleteInventorie.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmInventories.this.setVisible(true);
                if (currentInventory != null) {
                    populateTable();
                }
            }
        });

        obsoleteInventorie.setVisible(true);
    }

    private void onAddNewInventory() {
        FrmAddNewInventory addNewInventory = new FrmAddNewInventory(this, true, controller);
        this.setVisible(false);

        addNewInventory.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmInventories.this.setVisible(true);
                fillInventoryCombo();
                populateTable();
            }
        });

        addNewInventory.setVisible(true);
    }

    private void fillInventoryCombo() {
        if (controller != null && controller.getData() != null) {
            cmbInventories.removeAllItems();
            cmbInventories.addItem("Seleccione un inventario...");
            for (ec.edu.espe.finvory.model.Inventory inv : controller.getData().getInventories()) {
                cmbInventories.addItem(inv.getName());
            }
        }
    }

    private void onInventoryComboSelection() {
        String selectedName = (String) cmbInventories.getSelectedItem();
        controller.inventoryController.handleComboSelection(
                selectedName,
                txtCountryInventory,
                txtCityInventory,
                tabProducts,
                this
        );
    }

    public void setCurrentInventory(Inventory inventory) {
        this.currentInventory = inventory;
    }

    private void onClose() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbInventories;
    private javax.swing.JMenuItem itemAddNewInventory;
    private javax.swing.JMenuItem itemObsoleteProducts;
    private javax.swing.JMenuItem itemPrincipalMenu;
    private javax.swing.JMenuItem itemProducts;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblInventoryName;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JMenu mnuHandle;
    private javax.swing.JTable tabProducts;
    private javax.swing.JLabel txtCityInventory;
    private javax.swing.JLabel txtCountryInventory;
    // End of variables declaration//GEN-END:variables
}
