package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmInventories extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInventories.class.getName());

    private FinvoryController controller;
    private Inventory currentInventory = null;
    private FrmObsoleteInventories searchObsoleteInventoryWindow;
    private FrmAddNewInventory searchNewInventoryWindow;

    /**
     * Creates new form FrmInventories
     */
    public FrmInventories(FinvoryController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
        setupTableNonEditable();

        if (controller != null && controller.getData() != null) {
            System.out.println("VENTANA ABIERTA PARA USUARIO: " + controller.getData().getCompanyInfo().getUsername());
        } else {
            System.out.println("PELIGRO: CONTROLADOR O DATA SON NULL");
        }
    }

    public FrmInventories() {
        initComponents();
    }

    private void setupTableNonEditable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        tabProducts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFindInventory = new javax.swing.JButton();
        txtCountryInventory = new javax.swing.JLabel();
        txtCityInventory = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnReturnToMenu = new javax.swing.JButton();
        btnManageProducts = new javax.swing.JButton();
        btnHandleObsoleteInventory = new javax.swing.JButton();
        btnAddNewInventory = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Inventario:");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel2.setText("País:");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("Ciudad:");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel4.setText("Productos:");

        btnFindInventory.setBackground(new java.awt.Color(0, 123, 0));
        btnFindInventory.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnFindInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnFindInventory.setText("BUSCAR");
        btnFindInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFindInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInventoryActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 123, 0));
        btnCancel.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(242, 242, 242));
        btnCancel.setText("CANCELAR");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCountryInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCityInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(btnFindInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnCancel)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnFindInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountryInventory)
                    .addComponent(txtCityInventory)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(224, 224, 224));

        btnReturnToMenu.setBackground(new java.awt.Color(0, 123, 0));
        btnReturnToMenu.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnReturnToMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnToMenu.setText("ATRÁS");
        btnReturnToMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturnToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToMenuActionPerformed(evt);
            }
        });

        btnManageProducts.setBackground(new java.awt.Color(0, 123, 0));
        btnManageProducts.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnManageProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProducts.setText("GESTIONAR PRODUCTOS");
        btnManageProducts.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductsActionPerformed(evt);
            }
        });

        btnHandleObsoleteInventory.setBackground(new java.awt.Color(0, 123, 0));
        btnHandleObsoleteInventory.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnHandleObsoleteInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnHandleObsoleteInventory.setText("GESTIONAR OBSOLETOS");
        btnHandleObsoleteInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHandleObsoleteInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandleObsoleteInventoryActionPerformed(evt);
            }
        });

        btnAddNewInventory.setBackground(new java.awt.Color(0, 123, 0));
        btnAddNewInventory.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnAddNewInventory.setForeground(new java.awt.Color(242, 242, 242));
        btnAddNewInventory.setText("AGREGAR NUEVO INVENTARIO");
        btnAddNewInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddNewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewInventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnReturnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnManageProducts)
                .addGap(18, 18, 18)
                .addComponent(btnHandleObsoleteInventory)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnToMenu)
                    .addComponent(btnManageProducts)
                    .addComponent(btnHandleObsoleteInventory)
                    .addComponent(btnAddNewInventory))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 224, 224));

        tabProducts.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        tabProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "BARCODE", "COSTO", "P. STD", "P. PRM", "P. VIP", "STOCK", "STOCK OBS."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProducts);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHandleObsoleteInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandleObsoleteInventoryActionPerformed
        if (searchObsoleteInventoryWindow == null) {
            searchObsoleteInventoryWindow = new FrmObsoleteInventories(this, true);
        }

        searchObsoleteInventoryWindow.setVisible(true);
    }//GEN-LAST:event_btnHandleObsoleteInventoryActionPerformed

    private void btnAddNewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewInventoryActionPerformed
        FrmAddNewInventory win = new FrmAddNewInventory(this, true, this.controller);
        win.setVisible(true);
    }//GEN-LAST:event_btnAddNewInventoryActionPerformed

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        if (this.currentInventory != null) {
            new FrmProducts(controller, this.currentInventory).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Primero debe buscar y seleccionar un inventario.");
        }
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void btnFindInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInventoryActionPerformed
        String queryText = txtName.getText().trim();

        if (queryText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba un nombre.");
            return;
        }

        if (controller == null) {
            return;
        }

        try {
            ArrayList<Inventory> matches = controller.findInventoriesByPartialName(queryText);

            int cantidadEncontrada = (matches != null) ? matches.size() : 0;

            this.currentInventory = null;

            if (matches.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
                emptyFields();

            } else if (matches.size() == 1) {
                this.currentInventory = matches.get(0);
                fillInventoryDetails(this.currentInventory);
            } else {
                FrmInventorySelector selector = new FrmInventorySelector(this, true, matches);
                selector.setVisible(true);
                this.currentInventory = selector.getSelectedInventory();

                if (this.currentInventory != null) {
                    fillInventoryDetails(this.currentInventory);
                } else {
                    emptyFields();
                }
            }

        } catch (Exception e) {
            System.out.println("Mensaje: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error crítico: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFindInventoryActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        emptyFields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnReturnToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnReturnToMenuActionPerformed

    private void fillInventoryDetails(Inventory inv) {
        if (inv.getAddress() != null) {
            txtCountryInventory.setText(inv.getAddress().getCountry());
            txtCityInventory.setText(inv.getAddress().getCity());
        } else {
            txtCountryInventory.setText("Desconocido");
        }
        populateTable(inv);
    }

    private void populateTable(Inventory currentInventory) {
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);

        ArrayList<Product> globalProducts = controller.getData().getProducts();
        if (globalProducts == null || globalProducts.isEmpty()) {
            return;
        }

        float profit = controller.getData().getProfitPercentage();
        float dStd = controller.getData().getDiscountStandard();
        float dPrm = controller.getData().getDiscountPremium();
        float dVip = controller.getData().getDiscountVip();

        int coincidencias = 0;

        for (Product p : globalProducts) {
            String globalID = p.getId();

            int stock = currentInventory.getStock(globalID);

            if (stock == 0) {
                stock = currentInventory.getStock(globalID.trim());
            }

            if (stock >= 0) { 
                coincidencias++;

                int obsoleteStock = 0;
                if (controller.getData().getObsoleteInventory() != null) {
                    obsoleteStock = controller.getData().getObsoleteInventory().getStock(globalID);
                }

                model.addRow(new Object[]{
                    p.getId(),
                    p.getName(),
                    p.getBarcode(),
                    String.format("$%.2f", p.getBaseCostPrice()),
                    String.format("$%.2f", p.getPrice("STANDARD", profit, dStd, dPrm, dVip)),
                    String.format("$%.2f", p.getPrice("PREMIUM", profit, dStd, dPrm, dVip)),
                    String.format("$%.2f", p.getPrice("VIP", profit, dStd, dPrm, dVip)),
                    stock,
                    (double) obsoleteStock
                });
            }
        }
        
        tabProducts.revalidate();
        tabProducts.repaint();
    }

    private void emptyFields() {
        txtCountryInventory.setText("");
        txtCityInventory.setText("");
        DefaultTableModel model = (DefaultTableModel) tabProducts.getModel();
        model.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewInventory;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFindInventory;
    private javax.swing.JButton btnHandleObsoleteInventory;
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton btnReturnToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabProducts;
    private javax.swing.JLabel txtCityInventory;
    private javax.swing.JLabel txtCountryInventory;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
