package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.FinvoryApp;
import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.CompanyAccount;
import ec.edu.espe.finvory.utils.ValidationUtils;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmMainMenuPersonalAccount extends javax.swing.JFrame {

    private FinvoryController controller;

    public FrmMainMenuPersonalAccount() {
        initComponents();
        ButtonStyles.applyPrimaryStyle(btnFind);
        ButtonStyles.applyPrimaryStyle(btnInfo);
        ButtonStyles.applyPrimaryStyle(btnWhatsapp);
        FinvoryApp.setIcon(this);
    }

    public FrmMainMenuPersonalAccount(FinvoryController controller) {
        this.controller = controller;
        initComponents();
        ButtonStyles.applyPrimaryStyle(btnFind);
        ButtonStyles.applyPrimaryStyle(btnInfo);
        ButtonStyles.applyPrimaryStyle(btnWhatsapp);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setupTable();
    }

    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Nombre Producto", "Código Barras", "Stock Disponible"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabAllProducts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAllProducts = new javax.swing.JTable();
        btnInfo = new javax.swing.JButton();
        btnWhatsapp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemProfile = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCompany.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblCompany.setText("Empresa:");

        btnFind.setBackground(new java.awt.Color(0, 123, 0));
        btnFind.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnFind.setForeground(new java.awt.Color(242, 242, 242));
        btnFind.setText("BUSCAR");
        btnFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        tabAllProducts.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        tabAllProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Barcode", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tabAllProducts);

        btnInfo.setBackground(new java.awt.Color(0, 123, 0));
        btnInfo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(242, 242, 242));
        btnInfo.setText("MÁS INFO");
        btnInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnWhatsapp.setBackground(new java.awt.Color(0, 123, 0));
        btnWhatsapp.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnWhatsapp.setForeground(new java.awt.Color(242, 242, 242));
        btnWhatsapp.setText("Whatsapp");
        btnWhatsapp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatsappActionPerformed(evt);
            }
        });

        jMenu1.setText("Finvory");

        itemProfile.setText("Mi Perfil");
        itemProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProfileActionPerformed(evt);
            }
        });
        jMenu1.add(itemProfile);

        itemExit.setText("Salir");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuItem1.setText("Cerrar Programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCompany)
                .addGap(18, 18, 18)
                .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCompany)
                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWhatsapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        onExitToLogin();
    }//GEN-LAST:event_itemExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        onFindCompanyProducts();
    }//GEN-LAST:event_btnFindActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        onCloseProgram();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProfileActionPerformed
        onOpenPersonalProfile();
    }//GEN-LAST:event_itemProfileActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        onShowCompanyInfo();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatsappActionPerformed
        onContactCompany();
    }//GEN-LAST:event_btnWhatsappActionPerformed

    private void updateTable(List<Object[]> rows) {
        DefaultTableModel model = (DefaultTableModel) tabAllProducts.getModel();
        model.setRowCount(0);
        if (rows == null || rows.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron productos o la empresa no existe.", "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        for (Object[] row : rows) {
            model.addRow(row);
        }
    }

    private void onExitToLogin() {
        FrmLogin win = new FrmLogin(this.controller);
        win.setVisible(true);
        this.dispose();
    }

    private void onCloseProgram() {
        System.exit(0);
    }

    private void onOpenPersonalProfile() {
        FrmProfilePersonal profilePersonal = new FrmProfilePersonal(this, true, controller);
        this.setVisible(false);
        profilePersonal.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmMainMenuPersonalAccount.this.setVisible(true);
            }
        });
        profilePersonal.setVisible(true);
    }

    private void onFindCompanyProducts() {
        String companyName = txtCompany.getText().trim();

        String errorMsg = ValidationUtils.getSearchError(companyName);
        if (errorMsg != null) {
            JOptionPane.showMessageDialog(this, errorMsg, "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            List<Object[]> results = controller.productController.searchProductsByCompany(companyName);
            updateTable(results);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onShowCompanyInfo() {
        String companyName = txtCompany.getText().trim();

        if (ValidationUtils.isEmpty(companyName)) {
            JOptionPane.showMessageDialog(this, "Escriba el nombre de una empresa primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        CompanyAccount targetCompany = controller.userController.findCompanyByUsername(companyName);

        if (targetCompany != null) {
            String phone = targetCompany.getPhone();
            String email = targetCompany.getEmail();
            String info = String.format(
                    "Datos de %s:\nCelular/Teléfono: %s\nCorreo: %s",
                    targetCompany.getName(), phone, email
            );
            JOptionPane.showMessageDialog(this, info, "Información de Contacto", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró información de contacto para esta empresa.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onContactCompany() {
        String companyName = txtCompany.getText().trim();
        if (companyName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba el nombre de una empresa primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ec.edu.espe.finvory.model.CompanyAccount targetCompany = controller.userController.findCompanyByUsername(companyName);

        if (targetCompany != null && targetCompany.getPhone() != null) {
            String rawPhone = targetCompany.getPhone().replaceAll("[^0-9]", "");
            String finalPhone = "";

            if (rawPhone.length() == 10 && rawPhone.startsWith("0")) {
                finalPhone = "593" + rawPhone.substring(1);
            } else if (rawPhone.startsWith("593")) {
                finalPhone = rawPhone;
            } else if (rawPhone.length() == 9) {
                finalPhone = "593" + rawPhone;
            }

            try {
                String message = "Hola " + targetCompany.getName() + "!, estoy interesado en los productos que distribuyes.";
                String encodedMessage = message.replace(" ", "%20");
                String url = "https://api.whatsapp.com/send?phone=" + finalPhone + "&text=" + encodedMessage;

                if (java.awt.Desktop.isDesktopSupported()) {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(url));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al abrir el chat: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "La empresa no tiene un número registrado.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnWhatsapp;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemProfile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JTable tabAllProducts;
    private javax.swing.JTextField txtCompany;
    // End of variables declaration//GEN-END:variables
}
