package ec.edu.espe.finvory.view;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Inventory;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmObsoleteInventories extends JDialog {

    private FinvoryController controller;
    private Inventory specificInventory;

    public FrmObsoleteInventories(java.awt.Frame parent, boolean modal, FinvoryController controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);

        loadObsoleteTable();

    }

    private FrmProductReturns searchProductReturnsWindows;
    private FrmReassignedProduct searchReassignedProductWindows;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductID = new javax.swing.JLabel();
        txtIdProduct = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtProductAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabObsoleteProduct = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txtObsoleteStock = new javax.swing.JLabel();
        btnFindProduct = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInventories = new javax.swing.JMenu();
        itemInventories = new javax.swing.JMenuItem();
        mnuReturnsRecord = new javax.swing.JMenu();
        mnuProducts = new javax.swing.JMenu();
        itmDelete = new javax.swing.JMenuItem();
        itmReassign = new javax.swing.JMenuItem();
        itmReturns = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        lblProductID.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblProductID.setText("ID del producto:");

        lblLocation.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblLocation.setText("Ubicación:");

        tabObsoleteProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "MOTIVO", "FECHA", "CANTIDAD"
            }
        ));
        jScrollPane1.setViewportView(tabObsoleteProduct);

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        lblTitle.setText("INVENTARIO DE OBSOLETOS");

        lblQuantity.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblQuantity.setText("Cantidad:");

        btnFindProduct.setBackground(new java.awt.Color(0, 123, 0));
        btnFindProduct.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnFindProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnFindProduct.setText("BUSCAR");
        btnFindProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(txtProductAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProductID)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLocation)
                                .addGap(195, 195, 195)
                                .addComponent(lblQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObsoleteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFindProduct)
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(txtProductAddress)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductID)
                    .addComponent(txtIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindProduct))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(lblQuantity)
                    .addComponent(txtObsoleteStock))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mnuInventories.setText("Finvory");

        itemInventories.setText("Inventarios");
        itemInventories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInventoriesActionPerformed(evt);
            }
        });
        mnuInventories.add(itemInventories);

        jMenuBar1.add(mnuInventories);

        mnuReturnsRecord.setText("Gestión");

        mnuProducts.setText("Productos");

        itmDelete.setText("Desechar");
        itmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDeleteActionPerformed(evt);
            }
        });
        mnuProducts.add(itmDelete);

        itmReassign.setText("Reasignar");
        itmReassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReassignActionPerformed(evt);
            }
        });
        mnuProducts.add(itmReassign);

        mnuReturnsRecord.add(mnuProducts);

        itmReturns.setText("Registrar Devolución");
        itmReturns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReturnsActionPerformed(evt);
            }
        });
        mnuReturnsRecord.add(itmReturns);

        jMenuBar1.add(mnuReturnsRecord);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInventoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventoriesActionPerformed
        this.dispose();

    }//GEN-LAST:event_itemInventoriesActionPerformed

    private void itmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDeleteActionPerformed

        int row = tabObsoleteProduct.getSelectedRow();
        if (row == -1) {
            return;
        }

        String id = tabObsoleteProduct.getValueAt(row, 0).toString();
        String reason = tabObsoleteProduct.getValueAt(row, 2).toString();
        int currentQty = Integer.parseInt(tabObsoleteProduct.getValueAt(row, 4).toString());

        boolean validEntry = false;
        while (!validEntry) {
            String qtyStr = JOptionPane.showInputDialog(this, "Cantidad a desechar de la fila seleccionada:\n(Máximo: " + currentQty + ")");

            if (qtyStr == null) {
                break;
            }

            try {
                int quantity = Integer.parseInt(qtyStr.trim());

                if (quantity > 0 && quantity <= currentQty) {
                    if (controller.discardObsoleteProduct(id, quantity, reason)) {
                        JOptionPane.showMessageDialog(this, "Producto desechado.");
                        loadObsoleteTable();
                        validEntry = true;
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Error: Debe ser un número entero positivo máximo hasta " + currentQty,
                            "Cantidad Incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Error: Debe ser un número entero positivo máximo hasta " + currentQty,
                        "Entrada Inválida", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_itmDeleteActionPerformed

    private void itmReassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReassignActionPerformed

        int row = tabObsoleteProduct.getSelectedRow();
        if (row == -1) {
            return;
        }

        String id = tabObsoleteProduct.getValueAt(row, 0).toString();
        String name = tabObsoleteProduct.getValueAt(row, 1).toString();
        String reason = tabObsoleteProduct.getValueAt(row, 2).toString();
        int currentQuantity = Integer.parseInt(tabObsoleteProduct.getValueAt(row, 4).toString());

        String[] inventories = controller.getData().getInventories().stream()
                .map(Inventory::getName).toArray(String[]::new);

        String selectedInventory = (String) JOptionPane.showInputDialog(this, "Destino:", "Reasignar",
                JOptionPane.QUESTION_MESSAGE, null, inventories, inventories[0]);

        if (selectedInventory == null) {
            return;
        }

        boolean validEntry = false;
        while (!validEntry) {
            String quantityString = JOptionPane.showInputDialog(this, "Ingrese cantidad para " + name + "\n(Máximo permitido: " + currentQuantity + "):");

            if (quantityString == null) {
                break;
            }

            try {
                int quantity = Integer.parseInt(quantityString.trim());

                if (quantity > 0 && quantity <= currentQuantity) {
                    if (controller.reassignObsoleteProduct(id, quantity, selectedInventory, reason)) {
                        JOptionPane.showMessageDialog(this, "Reasignación exitosa.");
                        loadObsoleteTable();
                        validEntry = true;
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Error: Debe ser un número entero positivo máximo hasta " + currentQuantity,
                            "Cantidad Incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Error: Debe ser un número entero positivo máximo hasta " + currentQuantity,
                        "Entrada Inválida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_itmReassignActionPerformed

    private void itmReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReturnsActionPerformed
        FrmProductReturns productReturns = new FrmProductReturns(this, true, controller);
        productReturns.setVisible(true);

        loadObsoleteTable();
        this.setVisible(true);
    }//GEN-LAST:event_itmReturnsActionPerformed

    private void btnFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindProductActionPerformed

        String searchId = txtIdProduct.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tabObsoleteProduct.getModel();
        model.setRowCount(0);

        List<ec.edu.espe.finvory.model.ReturnedProduct> allReturns = controller.getData().getReturns();

        if (allReturns == null || allReturns.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay registros de devoluciones.");
            return;
        }

        boolean found = false;
        for (ec.edu.espe.finvory.model.ReturnedProduct returnedProduct : allReturns) {
            if (searchId.isEmpty() || returnedProduct.getProduct().getId().equalsIgnoreCase(searchId)) {
                Object[] row = {
                    returnedProduct.getProduct().getId(),
                    returnedProduct.getProduct().getName(),
                    returnedProduct.getReason(),
                    returnedProduct.getReturnDate().toString(),
                    String.valueOf(returnedProduct.getQuantity())
                };
                model.addRow(row);
                found = true;
            }
        }

        if (!found && !searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron devoluciones para el ID: " + searchId);
        }

    }//GEN-LAST:event_btnFindProductActionPerformed

    public void loadObsoleteTable() {
        DefaultTableModel model = (DefaultTableModel) tabObsoleteProduct.getModel();
        model.setRowCount(0);
        java.util.List<ec.edu.espe.finvory.model.ReturnedProduct> returnsList = controller.getData().getReturns();

        if (returnsList != null) {
            for (ec.edu.espe.finvory.model.ReturnedProduct returnedProduct : returnsList) {
                if (returnedProduct.getProduct() != null) {
                    Object[] row = {
                        returnedProduct.getProduct().getId(),
                        returnedProduct.getProduct().getName(),
                        returnedProduct.getReason(),
                        returnedProduct.getReturnDate().toString(),
                        String.valueOf(returnedProduct.getQuantity())
                    };
                    model.addRow(row);
                }
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindProduct;
    private javax.swing.JMenuItem itemInventories;
    private javax.swing.JMenuItem itmDelete;
    private javax.swing.JMenuItem itmReassign;
    private javax.swing.JMenuItem itmReturns;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu mnuInventories;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenu mnuReturnsRecord;
    private javax.swing.JTable tabObsoleteProduct;
    private javax.swing.JTextField txtIdProduct;
    private javax.swing.JLabel txtObsoleteStock;
    private javax.swing.JLabel txtProductAddress;
    // End of variables declaration//GEN-END:variables
}
