package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.FinvoryApp;
import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.controller.IProductActions;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maryuri Quiña, @ESPE
 */
public class FrmProducts extends javax.swing.JFrame {

    private final IProductActions productActionProcessor;
    private final FinvoryController controller;
    private Inventory specificInventory;

    /**
     * Creates new form FrmProducts
     *
     */
    public FrmProducts(IProductActions productActionProcessor, FinvoryController mainController, Inventory inventory) {
        this.productActionProcessor = productActionProcessor;
        this.controller = mainController;
        this.specificInventory = inventory;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setupTableSelection();
        loadProductTable();
        updateTitle();
        FinvoryApp.setIcon(this);
    }

    private void updateTitle() {
        if (specificInventory != null) {
            lblTitle.setText("Gestionando: " + specificInventory.getName());
        } else {
            lblTitle.setText("Catálogo Global de Productos");
        }
    }

    private void setupTableSelection() {
        jTableProducts.getSelectionModel().addListSelectionListener(e -> {
            boolean rowSelected = jTableProducts.getSelectedRow() != -1;
            btnEdit.setEnabled(rowSelected);
            btnDelete.setEnabled(rowSelected);
            boolean canMove = rowSelected && (specificInventory != null);
            btnMoveProduct.setEnabled(canMove);
        });
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnMoveProduct.setEnabled(false);
    }

    private void loadProductTable() {
        DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
        model.setRowCount(0);

        List<Object[]> productRows = productActionProcessor.getProductTableData(specificInventory);
        for (Object[] row : productRows) {
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductsList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMoveProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemInventories = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProductsList.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblProductsList.setText("Lista de productos:");

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Barcode", "Costo", "P.Standard", "P.Premium", "P.Vip", "Stock", "Stock (Obs)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProducts);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProductsList)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblProductsList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnEdit.setBackground(new java.awt.Color(0, 123, 0));
        btnEdit.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 123, 0));
        btnAdd.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Agregar nuevo producto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 123, 0));
        btnDelete.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMoveProduct.setBackground(new java.awt.Color(0, 123, 0));
        btnMoveProduct.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnMoveProduct.setForeground(new java.awt.Color(242, 242, 242));
        btnMoveProduct.setText("MOVER PRODUCTOS");
        btnMoveProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnEdit)
                .addGap(27, 27, 27)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoveProduct)
                .addGap(34, 34, 34)
                .addComponent(btnAdd)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(btnMoveProduct))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        lblTitle.setText("Productos Registados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblTitle)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenu1.setText("Finvory");

        itemInventories.setText("Inventarios");
        itemInventories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInventoriesActionPerformed(evt);
            }
        });
        jMenu1.add(itemInventories);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        onDeleteStock();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        openProductForm(null);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        onEditProduct();
    }//GEN-LAST:event_btnEditActionPerformed

    private void itemInventoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventoriesActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemInventoriesActionPerformed

    private void btnMoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveProductActionPerformed
        onMoveProductStock();
    }//GEN-LAST:event_btnMoveProductActionPerformed
    private void openProductForm(String productIdToEdit) {
        FrmAddNewProduct form;
        if (productIdToEdit == null) {
            form = new FrmAddNewProduct(this.controller, this.specificInventory);
        } else {
            form = new FrmAddNewProduct(this.controller, this.specificInventory, productIdToEdit);
        }
        this.setVisible(false);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadProductTable();
                setVisible(true);
            }
        });
        form.setVisible(true);
    }

    private void onDeleteStock() {
        int row = getSelectedRow();
        if (row == -1) {
            return;
        }

        if (specificInventory == null) {
            showWarning("Debe estar dentro de un inventario específico para borrar stock.");
            return;
        }

        String productId = getTableValue(row, 0);
        String productName = getTableValue(row, 1);

        if (!confirmDelete(productName, specificInventory.getName())) {
            return;
        }

        specificInventory.setStock(productId, 0);
        this.controller.saveData();
        loadProductTable();
        showInfo("Stock eliminado.");
    }

    private void onMoveProductStock() {
        if (!isInSpecificInventory()) {
            showWarning("Debe estar dentro de un inventario específico para mover productos.");
            return;
        }

        int row = getSelectedRow();
        if (row == -1) {
            return;
        }

        String productId = getTableValue(row, 0);
        String productName = getTableValue(row, 1);
        int currentStock = getTableInt(row, 7);

        if (currentStock <= 0) {
            showWarning("El producto no tiene stock disponible para mover.");
            return;
        }

        List<Inventory> targets = getTargetInventories();
        if (targets.isEmpty()) {
            showInfo("No existen otros inventarios creados para mover el producto.");
            return;
        }

        Inventory targetInventory = askTargetInventory(targets);
        if (targetInventory == null) {
            return;
        }

        if (!confirmMove(productName, currentStock, specificInventory.getName(), targetInventory.getName())) {
            return;
        }

        boolean success = this.controller.productController.handleMoveProductStock(specificInventory, targetInventory, productId);

        if (success) {
            showInfo("Producto movido exitosamente.");
            loadProductTable();
        } else {
            showError("Error al mover el producto.");
        }
    }

    private boolean isInSpecificInventory() {
        return specificInventory != null;
    }

    private int getSelectedRow() {
        return jTableProducts.getSelectedRow();
    }

    private String getTableValue(int row, int col) {
        Object v = jTableProducts.getValueAt(row, col);
        return v == null ? "" : v.toString();
    }

    private int getTableInt(int row, int col) {
        Object v = jTableProducts.getValueAt(row, col);
        if (v instanceof Integer) {
            return (Integer) v;
        }
        try {
            return Integer.parseInt(v.toString().trim());
        } catch (Exception e) {
            return 0;
        }
    }

    private boolean confirmDelete(String productName, String inventoryName) {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar '" + productName + "' del inventario '" + inventoryName + "'?\n"
                + "Esto dejará el stock en 0.",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );
        return confirm == JOptionPane.YES_OPTION;
    }

    private boolean confirmMove(String productName, int stock, String fromInv, String toInv) {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Mover todo el stock (" + stock + ") de '" + productName + "'\n"
                + "desde '" + fromInv + "' hacia '" + toInv + "'?",
                "Confirmar Movimiento",
                JOptionPane.YES_NO_OPTION
        );
        return confirm == JOptionPane.YES_OPTION;
    }

    private List<Inventory> getTargetInventories() {
        List<Inventory> allInventories = controller.getInventories();
        ArrayList<Inventory> targets = new ArrayList<>();

        if (allInventories == null) {
            return targets;
        }

        for (Inventory inv : allInventories) {
            if (inv == null || inv.getName() == null) {
                continue;
            }
            if (!inv.getName().equals(specificInventory.getName())) {
                targets.add(inv);
            }
        }
        return targets;
    }

    private Inventory askTargetInventory(List<Inventory> targets) {
        FrmInventorySelector selector = new FrmInventorySelector(this, true, new ArrayList<>(targets));
        selector.setVisible(true);
        return selector.getSelectedInventory();
    }

    private void showInfo(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showWarning(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Aviso", JOptionPane.WARNING_MESSAGE);
    }

    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void onEditProduct() {
        int row = getSelectedRow();
        if (row == -1) {
            showWarning("Seleccione un producto para editar.");
            return;
        }
        String productId = getTableValue(row, 0);
        openProductForm(productId);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMoveProduct;
    private javax.swing.JMenuItem itemInventories;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JLabel lblProductsList;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
