package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maryuri Quiña, @ESPE
 */
public class FrmProducts extends javax.swing.JFrame {

    private FinvoryController controller;
    private Inventory specificInventory;

    public FrmProducts(FinvoryController controller) {
        this(controller, null);
    }

    public FrmProducts(FinvoryController controller, Inventory inventory) {
        this.controller = controller;
        this.specificInventory = inventory;
        initComponents();
        this.setLocationRelativeTo(null);
        updateTitle();
        setupTableSelection();
        loadProductTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void updateTitle() {
        if (specificInventory != null) {
            jLabel1.setText("Gestionando: " + specificInventory.getName());
        } else {
            jLabel1.setText("Catálogo Global de Productos");
        }
    }

    private void setupTableSelection() {
        jTableProducts.getSelectionModel().addListSelectionListener(e -> {
            boolean rowSelected = jTableProducts.getSelectedRow() != -1;
            btnEdit.setEnabled(rowSelected);
            btnDelete.setEnabled(rowSelected);
            boolean canMove = rowSelected && (specificInventory != null);
            btnMoveProduct.setEnabled(canMove);
        });
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnMoveProduct.setEnabled(false);
    }

    private void loadProductTable() {
        DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
        model.setRowCount(0);

        if (controller == null) {
            return;
        }

        List<Object[]> rows = controller.getProductTableData(specificInventory);

        for (Object[] row : rows) {
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMoveProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemInventories = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel2.setText("Lista de productos:");

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Barcode", "Costo", "P.Standard", "P.Premium", "P.Vip", "Stock", "Stock (Obs)"
            }
        ));
        jScrollPane1.setViewportView(jTableProducts);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnEdit.setBackground(new java.awt.Color(0, 123, 0));
        btnEdit.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 123, 0));
        btnAdd.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Agregar nuevo producto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 123, 0));
        btnDelete.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMoveProduct.setBackground(new java.awt.Color(0, 123, 0));
        btnMoveProduct.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnMoveProduct.setForeground(new java.awt.Color(242, 242, 242));
        btnMoveProduct.setText("MOVER PRODUCTOS");
        btnMoveProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnEdit)
                .addGap(27, 27, 27)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoveProduct)
                .addGap(34, 34, 34)
                .addComponent(btnAdd)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(btnMoveProduct))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel1.setText("Productos Registados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenu1.setText("Finvory");

        itemInventories.setText("Inventarios");
        itemInventories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInventoriesActionPerformed(evt);
            }
        });
        jMenu1.add(itemInventories);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = jTableProducts.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        String productId = jTableProducts.getValueAt(selectedRow, 0).toString();
        String productName = jTableProducts.getValueAt(selectedRow, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar '" + productName + "' del inventario '" + specificInventory.getName() + "'?\n"
                + "Esto dejará el stock en 0.",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            specificInventory.setStock(productId, 0);
            controller.saveData();
            loadProductTable();
            JOptionPane.showMessageDialog(this, "Stock eliminado.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        openProductForm(null);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (specificInventory == null) {
            JOptionPane.showMessageDialog(this, "Solo se puede borrar stock desde un inventario específico.", "Acción no permitida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedRow = jTableProducts.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        String productId = jTableProducts.getValueAt(selectedRow, 0).toString();
        String productName = jTableProducts.getValueAt(selectedRow, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Desea dejar en 0 el stock de '" + productName + "' en este inventario?",
                "Confirmar Borrado de Stock",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = controller.handleZeroStock(specificInventory, productId);
            if (success) {
                loadProductTable();
                JOptionPane.showMessageDialog(this, "Stock eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar stock.");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void itemInventoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventoriesActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemInventoriesActionPerformed

    private void btnMoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveProductActionPerformed
        if (specificInventory == null) {
            JOptionPane.showMessageDialog(this, "Debe estar dentro de un inventario específico para mover productos.", "Acción no permitida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedRow = jTableProducts.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para mover.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String productId = jTableProducts.getValueAt(selectedRow, 0).toString();
        String productName = jTableProducts.getValueAt(selectedRow, 1).toString();
        int currentStock = (int) jTableProducts.getValueAt(selectedRow, 7);

        if (currentStock <= 0) {
            JOptionPane.showMessageDialog(this, "El producto no tiene stock disponible para mover.", "Stock Insuficiente", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<Inventory> allInventories = controller.getInventories();
        ArrayList<Inventory> targetInventories = new ArrayList<>();

        for (Inventory inventory : allInventories) {
            if (!inventory.getName().equals(specificInventory.getName())) {
                targetInventories.add(inventory);
            }
        }
        if (targetInventories.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen otros inventarios creados para mover el producto.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        FrmInventorySelector selector = new FrmInventorySelector(this, true, targetInventories);
        selector.setVisible(true);
        Inventory targetInventory = selector.getSelectedInventory();

        if (targetInventory != null) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Mover todo el stock (" + currentStock + ") de '" + productName + "'\n"
                    + "desde '" + specificInventory.getName() + "' hacia '" + targetInventory.getName() + "'?",
                    "Confirmar Movimiento", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                boolean success = controller.handleMoveProductStock(specificInventory, targetInventory, productId);

                if (success) {
                    JOptionPane.showMessageDialog(this, "Producto movido exitosamente.");
                    loadProductTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al mover el producto.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnMoveProductActionPerformed
    private void openProductForm(String productIdToEdit) {
        FrmAddNewProduct form;
        if (productIdToEdit == null) {
            form = new FrmAddNewProduct(this.controller, this.specificInventory);
        } else {
            form = new FrmAddNewProduct(this.controller, this.specificInventory, productIdToEdit);
        }
        this.setVisible(false);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadProductTable();
                setVisible(true);
            }
        });
        form.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMoveProduct;
    private javax.swing.JMenuItem itemInventories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducts;
    // End of variables declaration//GEN-END:variables
}
