package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Address;
import ec.edu.espe.finvory.model.CompanyAccount;
import ec.edu.espe.finvory.utils.ValidationUtils;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmProfileCompany extends javax.swing.JFrame {

    private final FinvoryController controller;
    private boolean isPasswordVisible = false;
    private final CardLayout cardLayout;

    public FrmProfileCompany(FinvoryController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
        this.cardLayout = (CardLayout) pnlCardsContainer.getLayout();
        setupDesign();
        loadCompanyData();
    }

    private void setupDesign() {
        icon.setIcon(ValidationUtils.getScaledIcon(getClass().getResource("/personal.jpg"), 161, 140));
        btnViewPassword.setIcon(ValidationUtils.getScaledIcon(getClass().getResource("/eyeClose.png"), 24, 24));
        btnUploadPhoto.setIcon(ValidationUtils.getScaledIcon(getClass().getResource("/upload.png"), 17, 17));
        cardLayout.show(pnlCardsContainer, "card2");
    }

    private void loadCompanyData() {
        if (controller.getData() == null || controller.getData().getCompanyInfo() == null) {
            return;
        }

        CompanyAccount company = controller.getData().getCompanyInfo();

        txtCompanyName.setText(company.getName());
        txtRuc.setText(company.getRuc());
        txtPhone.setText(company.getPhone());
        txtEmail.setText(company.getEmail());
        passCompany.setText(company.getPassword());
        txtRuc.setEditable(false);
        txtUserName.setText(company.getUsername());
        txtUserName.setEditable(false);

        Address address = company.getAddress();
        if (address != null) {
            txtCountry.setText(address.getCountry());
            txtCity.setText(address.getCity());
            txtStreet.setText(address.getStreet());
            txtStreetNumber.setText(address.getStreetNumber());
            txtZipCode.setText(address.getZipCode());
            txtRegion.setText(address.getRegion());
        }

        txtTaxRate.setText(controller.getData().getTaxRate().toString());
        txtProfit.setText(controller.getData().getProfitPercentage().toString());
        txtDiscPremium.setText(controller.getData().getDiscountPremium().toString());
        txtDiscStandar.setText(controller.getData().getDiscountStandard().toString());
        txtDiscVip.setText(controller.getData().getDiscountVip().toString());
        txtTaxRate.setEditable(false);
        txtProfit.setEditable(false);
        txtDiscPremium.setEditable(false);
        txtDiscStandar.setEditable(false);
        txtDiscVip.setEditable(false);

        try {
            java.net.URL imgUrl = null;
            String path = company.getLogoPath();

            if (path != null && new java.io.File(path).exists()) {
                imgUrl = new java.io.File(path).toURI().toURL();
            } else {
                imgUrl = getClass().getResource("/personal.jpg");
            }
            int fixedWidth = 161;
            int fixedHeight = 152;
            if (imgUrl != null) {
                icon.setIcon(ValidationUtils.getScaledIcon(imgUrl, fixedWidth, fixedHeight));
            }
        } catch (Exception e) {
            System.err.println("Error en persistencia visual: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSlidebar = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        btnGeneral = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnUploadPhoto = new javax.swing.JButton();
        pnlCardsContainer = new javax.swing.JPanel();
        cardGeneral = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        lblRUC = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passCompany = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnViewPassword = new javax.swing.JButton();
        cardAddress = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStreetNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        btnCancel1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        cardPrices = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTaxRate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtProfit = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDiscStandar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDiscPremium = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDiscVip = new javax.swing.JTextField();
        btnCancel2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlSlidebar.setBackground(new java.awt.Color(204, 204, 204));

        btnGeneral.setBackground(new java.awt.Color(0, 123, 0));
        btnGeneral.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnGeneral.setForeground(new java.awt.Color(242, 242, 242));
        btnGeneral.setText("GENERAL");
        btnGeneral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 123, 0));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("DIRECCION");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 123, 0));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("PRECIOS");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnUploadPhoto.setBackground(new java.awt.Color(242, 242, 242));
        btnUploadPhoto.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnUploadPhoto.setForeground(new java.awt.Color(242, 242, 242));
        btnUploadPhoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSlidebarLayout = new javax.swing.GroupLayout(pnlSlidebar);
        pnlSlidebar.setLayout(pnlSlidebarLayout);
        pnlSlidebarLayout.setHorizontalGroup(
            pnlSlidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSlidebarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSlidebarLayout.setVerticalGroup(
            pnlSlidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSlidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCardsContainer.setBackground(new java.awt.Color(224, 224, 224));
        pnlCardsContainer.setLayout(new java.awt.CardLayout());

        cardGeneral.setBackground(new java.awt.Color(224, 224, 224));

        lblTitle.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        lblTitle.setText("Información General");

        lblCompany.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblCompany.setText("Compañía:");

        lblRUC.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblRUC.setText("RUC:");

        lblPhone.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblPhone.setText("Celular:");

        lblEmail.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblEmail.setText("Email:");

        lblUser.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblUser.setText("Usuario:");

        lblPassword.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblPassword.setText("Contraseña:");

        passCompany.setText("jPasswordField1personal.jpgpersonal.jpgpersonal.jpgpersonal.jpg");

        btnCancel.setBackground(new java.awt.Color(0, 123, 0));
        btnCancel.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(242, 242, 242));
        btnCancel.setText("CANCELAR");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 123, 0));
        btnSave.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(242, 242, 242));
        btnSave.setText("GUARDAR CAMBIOS");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnViewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardGeneralLayout = new javax.swing.GroupLayout(cardGeneral);
        cardGeneral.setLayout(cardGeneralLayout);
        cardGeneralLayout.setHorizontalGroup(
            cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGeneralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompany)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(lblUser)
                    .addComponent(lblPassword)
                    .addGroup(cardGeneralLayout.createSequentialGroup()
                        .addGroup(cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passCompany, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle)
                    .addGroup(cardGeneralLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        cardGeneralLayout.setVerticalGroup(
            cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGeneralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRUC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(cardGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(20, 20, 20))
        );

        pnlCardsContainer.add(cardGeneral, "card2");

        cardAddress.setBackground(new java.awt.Color(224, 224, 224));

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel8.setText("Dirección General");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel9.setText("País:");

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel10.setText("Ciudad:");

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel11.setText("Calle:");

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel12.setText("Número de calle:");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel13.setText("Código Postal:");

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel14.setText("Región:");

        btnCancel1.setBackground(new java.awt.Color(0, 123, 0));
        btnCancel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(242, 242, 242));
        btnCancel1.setText("CANCELAR");
        btnCancel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        btnSave1.setBackground(new java.awt.Color(0, 123, 0));
        btnSave1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(242, 242, 242));
        btnSave1.setText("GUARDAR CAMBIOS");
        btnSave1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardAddressLayout = new javax.swing.GroupLayout(cardAddress);
        cardAddress.setLayout(cardAddressLayout);
        cardAddressLayout.setHorizontalGroup(
            cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCountry)
                    .addComponent(txtCity)
                    .addComponent(txtStreet)
                    .addGroup(cardAddressLayout.createSequentialGroup()
                        .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStreetNumber)
                    .addComponent(txtRegion)
                    .addGroup(cardAddressLayout.createSequentialGroup()
                        .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
            .addGroup(cardAddressLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAddressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave1)
                .addGap(18, 18, 18)
                .addComponent(btnCancel1)
                .addGap(31, 31, 31))
        );
        cardAddressLayout.setVerticalGroup(
            cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAddressLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(cardAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1)
                    .addComponent(btnSave1))
                .addGap(44, 44, 44))
        );

        pnlCardsContainer.add(cardAddress, "card3");

        cardPrices.setBackground(new java.awt.Color(224, 224, 224));

        jLabel15.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel15.setText("Configuración de Precios");

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel16.setText("Impuesto Aplicado:");

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel17.setText("Ganancia por Producto:");

        jLabel18.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel18.setText("Descuentos por Clientes:");

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel19.setText("Descuento Estandar:");

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel20.setText("Descuento Premium:");

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel21.setText("Descuento Vip:");

        btnCancel2.setBackground(new java.awt.Color(0, 123, 0));
        btnCancel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnCancel2.setForeground(new java.awt.Color(242, 242, 242));
        btnCancel2.setText("CANCELAR");
        btnCancel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardPricesLayout = new javax.swing.GroupLayout(cardPrices);
        cardPrices.setLayout(cardPricesLayout);
        cardPricesLayout.setHorizontalGroup(
            cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPricesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(cardPricesLayout.createSequentialGroup()
                        .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel18)
                    .addGroup(cardPricesLayout.createSequentialGroup()
                        .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiscStandar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDiscVip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtDiscPremium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPricesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel2)
                .addGap(59, 59, 59))
        );
        cardPricesLayout.setVerticalGroup(
            cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPricesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDiscStandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDiscPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDiscVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnCancel2)
                .addGap(43, 43, 43))
        );

        pnlCardsContainer.add(cardPrices, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSlidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCardsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSlidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
        ((java.awt.CardLayout) pnlCardsContainer.getLayout()).show(pnlCardsContainer, "card2");
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void btnViewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPasswordActionPerformed
        if (!isPasswordVisible) {
            passCompany.setEchoChar((char) 0);
            btnViewPassword.setIcon(ec.edu.espe.finvory.utils.ValidationUtils.getScaledIcon(
                    getClass().getResource("/eyeOpen.png"), 24, 24));
        } else {
            passCompany.setEchoChar('*');
            btnViewPassword.setIcon(ec.edu.espe.finvory.utils.ValidationUtils.getScaledIcon(
                    getClass().getResource("/eyeClose.png"), 24, 24));
        }
        isPasswordVisible = !isPasswordVisible;
    }//GEN-LAST:event_btnViewPasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtCompanyName.getText().trim();
        String ruc = txtRuc.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String pass = new String(passCompany.getPassword());
        String error = ValidationUtils.validateCustomerFields(name, ruc, phone, email, "COMPANY");
        if (error == null) {
            CompanyAccount company = controller.getData().getCompanyInfo();
            company.setName(name);
            company.setPhone(phone);
            company.setEmail(email);
            company.setPassword(pass);
            controller.saveData();
            JOptionPane.showMessageDialog(this, "Perfil de empresa actualizado con éxito.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, error, "Error de Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((java.awt.CardLayout) pnlCardsContainer.getLayout()).show(pnlCardsContainer, "card3");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        String country = txtCountry.getText().trim();
        String city = txtCity.getText().trim();
        String street = txtStreet.getText().trim();
        String streetNumber = txtStreetNumber.getText().trim();
        String zipCode = txtZipCode.getText().trim();
        String region = txtRegion.getText().trim();

        StringBuilder errorMsg = new StringBuilder();

        if (ValidationUtils.isEmpty(country)) {
            errorMsg.append("- El país es obligatorio.\n");
        } else if (!ValidationUtils.isTextOnly(country)) {
            errorMsg.append("- El país solo debe contener letras.\n");
        }
        if (ValidationUtils.isEmpty(city)) {
            errorMsg.append("- La ciudad es obligatoria.\n");
        } else if (!ValidationUtils.isTextOnly(city)) {
            errorMsg.append("- La ciudad solo debe contener letras.\n");
        }
        if (ValidationUtils.isEmpty(street)) {
            errorMsg.append("- La calle es obligatoria.\n");
        }
        if (!ValidationUtils.isEmpty(region) && !ValidationUtils.isValidRegion(region)) {
            errorMsg.append("- La región solo debe contener letras.\n");
        }
        if (!ValidationUtils.isEmpty(streetNumber) && !ValidationUtils.isValidStreetNumber(streetNumber)) {
            errorMsg.append("- El número de calle contiene caracteres no válidos.\n");
        }
        if (errorMsg.length() == 0) {
            CompanyAccount company = controller.getData().getCompanyInfo();
            Address address = company.getAddress();
            if (address == null) {
                address = new Address(country, city, street);
                company.setAddress(address);
            }
            address.setCountry(country);
            address.setCity(city);
            address.setStreet(street);
            address.setStreetNumber(streetNumber);
            address.setZipCode(zipCode);
            address.setRegion(region);
            controller.saveData();

            JOptionPane.showMessageDialog(this, "Dirección de empresa actualizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor corrija los siguientes errores:\n" + errorMsg.toString(),
                    "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancel2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ((java.awt.CardLayout) pnlCardsContainer.getLayout()).show(pnlCardsContainer, "card4");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        CompanyAccount company = controller.getData().getCompanyInfo();

        company.setName(txtCompanyName.getText().trim());
        company.setPhone(txtPhone.getText().trim());
        company.setEmail(txtEmail.getText().trim());
        company.setPassword(new String(passCompany.getPassword()));

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();

        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));

        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            String newPath = controller.userController.handleUploadPhoto(selectedFile, company.getUsername(), company.getLogoPath());

            if (newPath != null) {
                company.setLogoPath(newPath);
                controller.saveData();
                loadCompanyData();
                JOptionPane.showMessageDialog(this, "Foto y datos actualizados correctamente.");
            }
        }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCancel2;
    private javax.swing.JButton btnGeneral;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JButton btnViewPassword;
    private javax.swing.JPanel cardAddress;
    private javax.swing.JPanel cardGeneral;
    private javax.swing.JPanel cardPrices;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField passCompany;
    private javax.swing.JPanel pnlCardsContainer;
    private javax.swing.JPanel pnlSlidebar;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDiscPremium;
    private javax.swing.JTextField txtDiscStandar;
    private javax.swing.JTextField txtDiscVip;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtProfit;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtStreetNumber;
    private javax.swing.JTextField txtTaxRate;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
