package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.FinvoryApp;
import ec.edu.espe.finvory.controller.FinvoryController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;

/**
 *
 * @author Maryuri Quiña, The POOwer Rangers Of Programming
 */
public class FrmSalesReport extends javax.swing.JFrame {

    private String currentView = "SALES";
    private String currentReportType = "SALES_LIST";
    private FinvoryController controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSalesReport.class.getName());

    /**
     * Creates new form FrmSalesReport
     */
    public FrmSalesReport(FinvoryController controller) {
        this.controller = controller;
        initComponents();
        ButtonStyles.applyPrimaryStyle(btnExport);
        ButtonStyles.applyPrimaryStyle(btnFilter);
        ButtonStyles.applyPrimaryStyle(btnRefresh);
        this.setLocationRelativeTo(null);
        loadSalesTable();
        FinvoryApp.setIcon(this);
    }

    private void loadSalesTable() {
        DefaultTableModel model = (DefaultTableModel) tblSales.getModel();
        model.setRowCount(0);
        double totalSum = 0;

        List<Object[]> salesData = controller.saleController.getSalesTableData();
        if (salesData != null) {
            for (Object[] row : salesData) {
                model.addRow(row);
                totalSum += Double.parseDouble(row[4].toString().replace(",", "."));
            }
        }
        lblTotalVentas.setText("Total Ventas: $" + String.format("%.2f", totalSum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        jdEnd = new com.toedter.calendar.JDateChooser();
        jdStart = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        lblTotalVentas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGrossReport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuPopularProducts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        lblTitle.setText("Reporte de Ventas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExport.setBackground(new java.awt.Color(0, 123, 0));
        btnExport.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Exportar");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 123, 0));
        btnRefresh.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refrescar");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnExport)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(btnRefresh))
                .addGap(15, 15, 15))
        );

        lblStartDate.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblStartDate.setText("Fecha Inicio:");

        lblEndDate.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        lblEndDate.setText("Fecha Fin:");

        btnFilter.setBackground(new java.awt.Color(0, 123, 0));
        btnFilter.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter.setText("Filtrar");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEndDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jdStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addComponent(btnFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnFilter))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStartDate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Factura", "Fecha", "Cliente", "Subtotal", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblSales);

        lblTotalVentas.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        lblTotalVentas.setText("Total Ventas: $0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalVentas)
                .addGap(12, 12, 12))
        );

        jMenu1.setText("Finvory");

        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reporte");

        mnuGrossReport.setText("Ventas Brutas");
        mnuGrossReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGrossReportActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGrossReport);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");

        mnuPopularProducts.setText("Productos Demandados");
        mnuPopularProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPopularProductsActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPopularProducts);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        onCloseReport();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        onExportReport();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        onRefreshReport();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        onFilterByDates();
    }//GEN-LAST:event_btnFilterActionPerformed

    private void mnuGrossReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGrossReportActionPerformed
        onOpenGrossReport();
    }//GEN-LAST:event_mnuGrossReportActionPerformed

    private void mnuPopularProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPopularProductsActionPerformed
        onOpenPopularProducts();
    }//GEN-LAST:event_mnuPopularProductsActionPerformed

    private void onCloseReport() {
        this.dispose();
    }

    private void onExportSalesCsv() {
        String path = askCsvSavePath();
        if (path == null) {
            return;
        }

        String reportTitle = "REPORTE DETALLADO DE VENTAS";
        String[] headers = {"ID Factura", "Fecha", "Cliente", "Subtotal", "Total"};

        java.util.List<Object[]> dataRows = extractTableRows(tblSales);
        controller.exportController.exportTableWithDateToCSV(path, reportTitle, headers, dataRows);

        JOptionPane.showMessageDialog(this, "El reporte de ventas se ha exportado con éxito.");
    }

    private String askCsvSavePath() {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte de Ventas");

        if (fileChooser.showSaveDialog(this) != javax.swing.JFileChooser.APPROVE_OPTION) {
            return null;
        }

        String path = fileChooser.getSelectedFile().getAbsolutePath();
        if (!path.toLowerCase().endsWith(".csv")) {
            path += ".csv";
        }
        return path;
    }

    private java.util.List<Object[]> extractTableRows(javax.swing.JTable table) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        java.util.List<Object[]> dataRows = new java.util.ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object[] row = new Object[model.getColumnCount()];
            for (int j = 0; j < model.getColumnCount(); j++) {
                row[j] = model.getValueAt(i, j);
            }
            dataRows.add(row);
        }

        return dataRows;
    }

    private void onRefreshReport() {
        resetSalesTableHeaders();
        clearDateFilters();
        currentReportType = "SALES_LIST";
        loadSalesTable();
    }

    private void resetSalesTableHeaders() {
        DefaultTableModel model = (DefaultTableModel) tblSales.getModel();
        String[] headers = {"ID Factura", "Fecha", "Cliente", "Subtotal", "Total"};
        model.setColumnIdentifiers(headers);
    }

    private void clearDateFilters() {
        jdStart.setDate(null);
        jdEnd.setDate(null);
    }

    private void onFilterByDates() {
        if (!areDatesSelected()) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione ambas fechas.");
            return;
        }

        resetSalesTableHeaders();
        clearSalesTableRows();
        currentReportType = "SALES_LIST";

        java.time.LocalDate start = toLocalDate(jdStart.getDate());
        java.time.LocalDate end = toLocalDate(jdEnd.getDate());

        double totalSum = fillSalesBetweenDates(start, end);
        lblTotalVentas.setText("TOTAL VENTAS: $" + String.format("%.2f", totalSum));
    }

    private boolean areDatesSelected() {
        return jdStart.getDate() != null && jdEnd.getDate() != null;
    }

    private void clearSalesTableRows() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSales.getModel();
        model.setRowCount(0);
    }

    private java.time.LocalDate toLocalDate(java.util.Date date) {
        return date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    }

    private double fillSalesBetweenDates(java.time.LocalDate start, java.time.LocalDate end) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSales.getModel();

        double totalSum = 0;

        if (controller == null || controller.getData() == null || controller.getData().getInvoices() == null) {
            return 0;
        }

        for (ec.edu.espe.finvory.model.InvoiceSim invoice : controller.getData().getInvoices()) {
            if (invoice == null || invoice.getDate() == null) {
                continue;
            }

            java.time.LocalDate date = invoice.getDate();
            if (!date.isBefore(start) && !date.isAfter(end)) {
                model.addRow(new Object[]{
                    invoice.getId(),
                    invoice.getDate().toString(),
                    invoice.getCustomer().getName(),
                    String.format("%.2f", invoice.getSubtotal()),
                    String.format("%.2f", invoice.getTotal())
                });
                totalSum += invoice.getTotal().doubleValue();
            }
        }

        return totalSum;
    }

    private void onOpenGrossReport() {
        FrmGrossReport gross = new FrmGrossReport(this.controller);

        gross.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                FrmSalesReport.this.setVisible(true);
            }
        });

        gross.setVisible(true);
        FrmSalesReport.this.setVisible(false);
    }

    private void onOpenPopularProducts() {
        FrmPopularProducts frmPopular = new FrmPopularProducts(this.controller);
        frmPopular.setVisible(true);
    }

    private void onExportReport() {
        var format = ec.edu.espe.finvory.controller.report.ReportUiHelper.askFormat(this);
        if (format == null) {
            return;
        }

        String path = ec.edu.espe.finvory.controller.report.ReportUiHelper.askSavePath(
                this,
                "Guardar Reporte de Ventas",
                format
        );
        if (path == null) {
            return;
        }

        String reportTitle = "REPORTE DETALLADO DE VENTAS";
        String[] headers = ec.edu.espe.finvory.controller.report.ReportUiHelper.extractHeaders(tblSales);
        java.util.List<Object[]> rows = ec.edu.espe.finvory.controller.report.ReportUiHelper.extractRows(tblSales);

        ec.edu.espe.finvory.controller.report.ReportExporter exporter
                = new ec.edu.espe.finvory.controller.report.ReportExporter(null);

        try {
            if (format == ec.edu.espe.finvory.controller.report.ReportUiHelper.Format.CSV) {
                exporter.setStrategy(new ec.edu.espe.finvory.controller.report.CsvReportExportStrategy(controller.exportController));
            } else {
                exporter.setStrategy(new ec.edu.espe.finvory.controller.report.PdfReportExportStrategy());
            }

            exporter.export(path, reportTitle, headers, rows);
            javax.swing.JOptionPane.showMessageDialog(this, "Reporte exportado con éxito.");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al exportar: " + ex.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Error exportando reporte", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdEnd;
    private com.toedter.calendar.JDateChooser jdStart;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JMenuItem mnuGrossReport;
    private javax.swing.JMenuItem mnuPopularProducts;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables
}
