package ec.edu.espe.finvory.view;

import ec.edu.espe.finvory.FinvoryApp;
import ec.edu.espe.finvory.controller.FinvoryController;
import ec.edu.espe.finvory.model.Customer;
import ec.edu.espe.finvory.model.Inventory;
import ec.edu.espe.finvory.model.Product;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmSaleInvoice extends javax.swing.JFrame {

    private FinvoryController controller;
    private Customer selectedCustomer = null;
    private HashMap<Product, HashMap<Inventory, Integer>> currentCart = new HashMap<>();
    private BigDecimal subtotalVal = BigDecimal.ZERO;
    private BigDecimal taxVal = BigDecimal.ZERO;
    private BigDecimal totalVal = BigDecimal.ZERO;

    public FrmSaleInvoice() {
        initComponents();
        FinvoryApp.setIcon(this);
        
    }

    public FrmSaleInvoice(FinvoryController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
        initializeInvoiceData();
        setupFieldsState();
        FinvoryApp.setIcon(this);
        
    }

    private void initializeInvoiceData() {
        LocalDate today = LocalDate.now();
        txtDate.setText(today.toString());
        if (controller != null) {
            String invoiceId = controller.saleController.generateNextInvoiceId();
            txtSale.setText(invoiceId);
        } else {
            txtSale.setText("ERR-CTRL");
        }
        txtTypeClient.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPhone.setEnabled(false);
        txtDate.setEnabled(false);
        txtSale.setEnabled(false);
        txtTotalSub.setEnabled(false);
        txTax.setEnabled(false);
        txtTotal.setEnabled(false);
    }

    private void setupFieldsState() {
        txtPhone.setText("");
        txtEmail.setText("");
        txtClientType.setText("");
    }

    public void addProductToCart(Product product, Inventory sourceInventory, int quantity) {
        if (selectedCustomer == null) {
            JOptionPane.showMessageDialog(this, "Primero debe seleccionar un cliente para calcular los precios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        currentCart.putIfAbsent(product, new HashMap<>());
        Map<Inventory, Integer> inventoryMap = currentCart.get(product);
        inventoryMap.put(sourceInventory, inventoryMap.getOrDefault(sourceInventory, 0) + quantity);
        BigDecimal profit = controller.getData().getProfitPercentage();
        BigDecimal dStd = controller.getData().getDiscountStandard();
        BigDecimal dPrm = controller.getData().getDiscountPremium();
        BigDecimal dVip = controller.getData().getDiscountVip();

        BigDecimal unitPrice = product.getPrice(selectedCustomer.getClientType(), profit, dStd, dPrm, dVip);
        BigDecimal lineTotal = unitPrice.multiply(new BigDecimal(quantity)).setScale(2, RoundingMode.HALF_UP);

        DefaultTableModel model = (DefaultTableModel) tabProductList.getModel();
        if (currentCart.size() == 1 && inventoryMap.size() == 1 && model.getValueAt(0, 0) == null) {
            model.setRowCount(0);
        }

        model.addRow(new Object[]{
            product.getId(),
            quantity,
            product.getName(),
            lineTotal.doubleValue()
        });

        updateTotals(lineTotal);
    }

    private void updateTotals(BigDecimal lineAmountToAdd) {
        subtotalVal = subtotalVal.add(lineAmountToAdd);
        BigDecimal taxRate = controller.getData().getTaxRate();
        taxVal = subtotalVal.multiply(taxRate).setScale(2, RoundingMode.HALF_UP);
        totalVal = subtotalVal.add(taxVal).setScale(2, RoundingMode.HALF_UP);
        txtTotalSub.setText(subtotalVal.toString());
        txTax.setText(taxVal.toString());
        txtTotal.setText(totalVal.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        lblSaleNumber = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtSalesNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTypeOfCustomer = new javax.swing.JLabel();
        txtClientType = new javax.swing.JLabel();
        lblPaymentType = new javax.swing.JLabel();
        radPaymentMethodCash = new javax.swing.JRadioButton();
        radPaymentMethodTransfer = new javax.swing.JRadioButton();
        radPaymentMethodCheque = new javax.swing.JRadioButton();
        btnFind = new javax.swing.JButton();
        txtSale = new javax.swing.JTextField();
        txtDate = new javax.swing.JButton();
        txtPhone = new javax.swing.JTextField();
        txtTypeClient = new javax.swing.JTextField();
        lblCustomer = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnHandleList = new javax.swing.JButton();
        btnConfirmSale = new javax.swing.JButton();
        btnCancelSale = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotalSub = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotalSale = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        txtTax = new javax.swing.JLabel();
        txtTotalSale = new javax.swing.JLabel();
        txtTotalSub = new javax.swing.JTextField();
        txTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProductList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(224, 224, 224));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 188, 224)));
        panel.setForeground(new java.awt.Color(162, 188, 224));

        lblSaleNumber.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblSaleNumber.setText("Venta No.");

        lblDate.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblDate.setText("Fecha:");

        lblCI.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblCI.setText("CI:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblName.setText("Nombre:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblPhone.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblPhone.setText("Celular:");

        lblEmail.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblTypeOfCustomer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblTypeOfCustomer.setText("Tipo de Cliente:");

        lblPaymentType.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblPaymentType.setText("Tipo de Pago:");

        radPaymentMethodCash.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        radPaymentMethodCash.setText("efectivo");
        radPaymentMethodCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPaymentMethodCashActionPerformed(evt);
            }
        });

        radPaymentMethodTransfer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        radPaymentMethodTransfer.setText("transferencia");
        radPaymentMethodTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPaymentMethodTransferActionPerformed(evt);
            }
        });

        radPaymentMethodCheque.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        radPaymentMethodCheque.setText("cheque");

        btnFind.setBackground(new java.awt.Color(0, 123, 0));
        btnFind.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnFind.setForeground(new java.awt.Color(242, 242, 242));
        btnFind.setText("BUSCAR");
        btnFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        txtTypeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeClientActionPerformed(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblCustomer.setText("CLIENTE:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblSaleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCustomer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSalesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPaymentType)
                    .addComponent(lblCI)
                    .addComponent(lblPhone)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtPhone)
                            .addComponent(txtId))
                        .addGap(29, 29, 29)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTypeOfCustomer))
                        .addGap(12, 12, 12)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTypeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(radPaymentMethodCash)
                        .addGap(18, 18, 18)
                        .addComponent(radPaymentMethodTransfer)
                        .addGap(32, 32, 32)
                        .addComponent(radPaymentMethodCheque)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalesNumber)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(txtClientType)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSaleNumber)
                                .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDate))
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomer)
                        .addGap(5, 5, 5)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(lblCI)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone)
                                    .addComponent(lblTypeOfCustomer)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTypeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radPaymentMethodTransfer)
                                .addComponent(radPaymentMethodCash)
                                .addComponent(lblPaymentType))
                            .addComponent(radPaymentMethodCheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(0, 7, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(224, 224, 224));
        jPanel2.setForeground(new java.awt.Color(162, 188, 224));

        btnHandleList.setBackground(new java.awt.Color(0, 123, 0));
        btnHandleList.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnHandleList.setForeground(new java.awt.Color(255, 255, 255));
        btnHandleList.setText("GESTIONAR LISTA");
        btnHandleList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHandleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandleListActionPerformed(evt);
            }
        });

        btnConfirmSale.setBackground(new java.awt.Color(0, 123, 0));
        btnConfirmSale.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnConfirmSale.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmSale.setText("CONFIRMAR");
        btnConfirmSale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSaleActionPerformed(evt);
            }
        });

        btnCancelSale.setBackground(new java.awt.Color(0, 123, 0));
        btnCancelSale.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnCancelSale.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelSale.setText("CANCELAR");
        btnCancelSale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSaleActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblTotal.setText("TOTAL");

        lblTotalSub.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblTotalSub.setText("Subtotal:");

        lblTax.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblTax.setText("Impuesto:");

        lblTotalSale.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblTotalSale.setText("Total venta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConfirmSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelSale))
                    .addComponent(btnHandleList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalSub)
                    .addComponent(lblTax)
                    .addComponent(lblTotalSale))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalSale, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTotalSub, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txTax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHandleList)
                    .addComponent(lblTotalSub)
                    .addComponent(txtSubtotal)
                    .addComponent(txtTotalSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTax)
                    .addComponent(txtTax)
                    .addComponent(txTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmSale)
                    .addComponent(btnCancelSale)
                    .addComponent(lblTotalSale)
                    .addComponent(txtTotalSale)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 224, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 184, 235)));
        jPanel3.setForeground(new java.awt.Color(162, 188, 224));

        tabProductList.setBackground(new java.awt.Color(242, 242, 242));
        tabProductList.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        tabProductList.setForeground(new java.awt.Color(162, 188, 224));
        tabProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CANTIDAD", "DESCRIPCION", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProductList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setText("Finvory");

        jMenuItem1.setText("Menú Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSaleActionPerformed
        onCancelSale();
    }//GEN-LAST:event_btnCancelSaleActionPerformed

    private void btnConfirmSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSaleActionPerformed
        onConfirmSale();
    }//GEN-LAST:event_btnConfirmSaleActionPerformed

    private void btnHandleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandleListActionPerformed
        onManageProductList();
    }//GEN-LAST:event_btnHandleListActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        onFindCustomer();
    }//GEN-LAST:event_btnFindActionPerformed

    private void radPaymentMethodTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPaymentMethodTransferActionPerformed
        onPaymentTransferToggle();
    }//GEN-LAST:event_radPaymentMethodTransferActionPerformed

    private void radPaymentMethodCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPaymentMethodCashActionPerformed
        onPaymentCashToggle();
    }//GEN-LAST:event_radPaymentMethodCashActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtTypeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeClientActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        onGoToMainMenu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void emptyFields() {
        this.selectedCustomer = null;
        this.currentCart.clear();
        this.subtotalVal = BigDecimal.ZERO;
        this.taxVal = BigDecimal.ZERO;
        this.totalVal = BigDecimal.ZERO;
        txtName.setText("");
        txtId.setText("");
        txtTypeClient.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtTotalSub.setText("");
        txTax.setText("");
        txtTotal.setText("");
        DefaultTableModel model = (DefaultTableModel) tabProductList.getModel();
        model.setRowCount(0);
    }

    private void loadCustomerIntoForm(Customer customer) {
        this.selectedCustomer = customer;
        txtId.setText(customer.getIdentification());
        txtName.setText(customer.getName());
        txtTypeClient.setText(customer.getClientType());
        txtEmail.setText(customer.getEmail());
        txtPhone.setText(customer.getPhone());
        JOptionPane.showMessageDialog(this, "Cliente cargado: " + customer.getName(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void onCancelSale() {
        if (!confirmCancelSale()) {
            return;
        }
        resetInvoiceForm();
        this.dispose();
    }

    private boolean confirmCancelSale() {
        int option = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de cancelar la venta? Los datos se perderán.",
                "Confirmar Cancelación",
                JOptionPane.YES_NO_OPTION
        );
        return option == JOptionPane.YES_OPTION;
    }

    private void onConfirmSale() {
        if (!isSaleDataValid()) {
            showMissingDataError();
            return;
        }

        String payment = getSelectedPaymentMethod();

        boolean success = controller.saleController.handleNewSale(selectedCustomer, currentCart, payment);

        if (success) {
            showSaleSuccess();
            resetInvoiceForm();
            this.dispose();
        } else {
            showSaleError();
        }
    }

    private boolean isSaleDataValid() {
        return selectedCustomer != null && !currentCart.isEmpty();
    }

    private void showMissingDataError() {
        JOptionPane.showMessageDialog(
                this,
                "Faltan datos (Cliente o Productos).",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    private String getSelectedPaymentMethod() {
        if (radPaymentMethodTransfer.isSelected()) {
            return "TRANSFERENCIA";
        }
        if (radPaymentMethodCheque.isSelected()) {
            return "CHEQUE POSTFECHADO";
        }
        return "EFECTIVO";
    }

    private void showSaleSuccess() {
        JOptionPane.showMessageDialog(
                this,
                "¡Venta registrada y guardada en la nube exitosamente!",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    private void showSaleError() {
        JOptionPane.showMessageDialog(
                this,
                "Error al guardar la venta.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    private void onManageProductList() {
        if (!isCustomerSelected()) {
            showSelectCustomerWarning();
            return;
        }
        openEditProductListDialog();
    }

    private boolean isCustomerSelected() {
        return selectedCustomer != null;
    }

    private void showSelectCustomerWarning() {
        JOptionPane.showMessageDialog(
                this,
                "Por favor seleccione un cliente antes de agregar productos.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );
    }

    private void openEditProductListDialog() {
        FrmEditProductListOnInvoice dialog = new FrmEditProductListOnInvoice(this, true, controller);
        dialog.setVisible(true);
    }

    private void onFindCustomer() {
        if (!isControllerReady()) {
            showControllerNotReadyError();
            return;
        }

        String query = buildCustomerQuery();
        if (query == null) {
            showEmptySearchWarning();
            return;
        }

        java.util.ArrayList<Customer> matches = controller.customerController.findCustomersByQuery(query);
        handleCustomerSearchResults(matches);
    }

    private boolean isControllerReady() {
        return controller != null;
    }

    private void showControllerNotReadyError() {
        JOptionPane.showMessageDialog(
                this,
                "Error: Controlador no inicializado.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    private String buildCustomerQuery() {
        String idQuery = txtId.getText().trim();
        String nameQuery = txtName.getText().trim();

        if (!idQuery.isEmpty()) {
            return idQuery;
        }
        if (!nameQuery.isEmpty()) {
            return nameQuery;
        }
        return null;
    }

    private void showEmptySearchWarning() {
        JOptionPane.showMessageDialog(
                this,
                "Ingrese ID o Nombre para buscar.",
                "Campo Vacío",
                JOptionPane.WARNING_MESSAGE
        );
    }

    private void handleCustomerSearchResults(java.util.ArrayList<Customer> matches) {
        if (matches == null || matches.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron clientes.",
                    "Sin Resultados",
                    JOptionPane.INFORMATION_MESSAGE
            );
            resetInvoiceForm();
            return;
        }

        if (matches.size() == 1) {
            loadCustomerIntoForm(matches.get(0));
            return;
        }

        openCustomerSelector(matches);
    }

    private void openCustomerSelector(java.util.ArrayList<Customer> matches) {
        FrmCustomerSelector selector = new FrmCustomerSelector(this, true, matches);
        selector.setVisible(true);

        Customer selected = selector.getSelectedCustomer();
        if (selected != null) {
            loadCustomerIntoForm(selected);
        }
    }

    private void onPaymentTransferToggle() {
        updatePaymentOptionsState(radPaymentMethodTransfer, radPaymentMethodCash, radPaymentMethodCheque);
    }

    private void onPaymentCashToggle() {
        updatePaymentOptionsState(radPaymentMethodCash, radPaymentMethodTransfer, radPaymentMethodCheque);
    }

    private void updatePaymentOptionsState(javax.swing.JRadioButton selected,
                                          javax.swing.JRadioButton opt1,
                                          javax.swing.JRadioButton opt2) {

        boolean isSelected = selected.isSelected();
        opt1.setEnabled(!isSelected);
        opt2.setEnabled(!isSelected);
    }

    private void onGoToMainMenu() {
        this.dispose();
    }

    /**
     * Alias para que NO tengas que cambiar tu método original emptyFields()
     * (así no rompes nada del proyecto)
     */
    private void resetInvoiceForm() {
        emptyFields();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelSale;
    private javax.swing.JButton btnConfirmSale;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHandleList;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPaymentType;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSaleNumber;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalSale;
    private javax.swing.JLabel lblTotalSub;
    private javax.swing.JLabel lblTypeOfCustomer;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radPaymentMethodCash;
    private javax.swing.JRadioButton radPaymentMethodCheque;
    private javax.swing.JRadioButton radPaymentMethodTransfer;
    private javax.swing.JTable tabProductList;
    private javax.swing.JTextField txTax;
    private javax.swing.JLabel txtClientType;
    private javax.swing.JButton txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSale;
    private javax.swing.JLabel txtSalesNumber;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtTotalSale;
    private javax.swing.JTextField txtTotalSub;
    private javax.swing.JTextField txtTypeClient;
    // End of variables declaration//GEN-END:variables
}
